spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/Database
    username: system
    password: password
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none