server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: inventoryModule
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**